apiVersion: v1
kind: Service
metadata:
  labels:
    app: mekanbulfrontend
  name: mekanbulfrontend
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    app: mekanbulfrontend
