require("dotenv").config();
var express = require("express");
const passport = require("passport");
require("./models/db");
require("./config/passport");
var app = express();
app.use(passport.initialize());
var apiRouter = require("./routes/index");
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use("/api", apiRouter);
module.exports = app;